import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import Header from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SERP Preview',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es'>
      <body
        className={
          inter.className + ' bg-gradient-to-tr from-background to-accent'
        }
      >
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <Header />
          <main className='min-h-screen p-2'>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
